---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "fancy-ruby-ns-samples.example.com"
spec:
  group: "example.com"
  names:
    plural: "fancy-ruby-ns-samples"
    singular: "fancy-ruby-ns-sample"
    kind: "FancyRubyNsSample"
  scope: "Namespaced"
  versions:
  - name: "v1alpha1"
    schema:
      openAPIV3Schema:
        required: ["spec"]
        properties:
          spec:
            required: ["sampleName"]
            properties:
              sampleName:
                type: "string"
                minimum: 1
            type: object
          status:
            properties:
              message:
                type: "string"
                minimum: 1
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
