---
apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "fancy-ruby-ns-samples.example.com"
spec:
  group: "example.com"
  version: "v1alpha1"
  scope: "Namespaced"
  subresources:
    status: {}
  names:
    plural: "fancy-ruby-ns-samples"
    singular: "fancy-ruby-ns-sample"
    kind: "FancyRubyNsSample"
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["sampleName"]
          properties:
            sampleName:
              type: "string"
              minimum: 1
        status:
          type: object
          properties:
            message:
              type: "string"
              minimum: 1
