rubygems:
  script:
    - gem build kubernetes-operator.gemspec
    - mkdir ~/.gem
    - export RUBYGEMS_APIKEY_WITH_SPACE=" $RUBYGEMS_APIKEY"
    - echo ":rubygems_api_key:$RUBYGEMS_APIKEY_WITH_SPACE" > ~/.gem/credentials
    - chmod 0600 /root/.gem/credentials
    - gem push `ls -1 kubernetes-operator-*.gem`
  only:
    changes:
      - lib/kubernetes-operator.rb
      - kubernetes-operator.gemspec
