stages:
  - release
  - documentation

rubygems:
  stage: release
  script:
    - gem build kubernetes-operator.gemspec
    - mkdir ~/.gem
    - export RUBYGEMS_APIKEY_WITH_SPACE=" $RUBYGEMS_APIKEY"
    - echo ":rubygems_api_key:$RUBYGEMS_APIKEY_WITH_SPACE" > ~/.gem/credentials
    - chmod 0600 /root/.gem/credentials
    - gem push `ls -1 kubernetes-operator-*.gem`
  only:
    changes:
      - lib/kubernetes-operator.rb
      - kubernetes-operator.gemspec

pages:
  stage: documentation
  tags:
    - iat
    - k8s
    - sparkleformation
  script:
    - gem build kubernetes-operator.gemspec
    - gem install yard
    - yard doc --files `ls -1 | grep .gem | grep -v .gemspec`
    - rm -rf public
    - mv doc public
  artifacts:
    paths:
    - public