
apiVersion: v1
firstTimestamp: "2020-03-25T20:26:22Z"
involvedObject:
  apiVersion: example.com/v1alpha1
  kind: FancyRubySample
  name: my-sample
  #namespace: operations--nil--default # nil for cluster resources
  resourceVersion: "5827387"
  uid: 176a2978-ebe4-4626-9098-c76a4bcbfc72
kind: Event
message: My first event
metadata:
  name: my-sample.12345 # random
  namespace: default # cr namespace or default for cluster resources
reason: TestEvent # free string
source:
  component: ruby-kubernetes-operator # free string
type: Normal # free string
